# Generated by Django 2.2.3 on 2019-07-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroname', models.CharField(max_length=30)),
                ('herolv', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('atk', models.IntegerField(max_length=10)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.HeroInfo')),
            ],
        ),
    ]
