# Generated by Django 2.2.3 on 2019-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='herolv',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skillsinfo',
            name='atk',
            field=models.IntegerField(default=10),
        ),
    ]
