# Generated by Django 2.2.3 on 2019-07-17 02:44

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='body',
            field=DjangoUeditor.models.UEditorField(),
        ),
        migrations.AlterField(
            model_name='recyclinguser',
            name='phone',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
    ]
