# Generated by Django 2.2.3 on 2019-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190717_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='文章', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='recyclinguser',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='Zipcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='carbonreduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='integral',
            field=models.IntegerField(default=0),
        ),
    ]
