# Generated by Django 2.2.3 on 2019-07-17 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190717_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.ActivityTags'),
            preserve_default=False,
        ),
    ]
