# Generated by Django 2.2.3 on 2019-07-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_onegoods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('userphone', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('appointment_time', models.CharField(max_length=50)),
                ('over_time', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.RecyclingUser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodname', models.CharField(max_length=200)),
                ('goodprice', models.IntegerField()),
                ('integral', models.IntegerField(default=0)),
                ('carbonreduction', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Order')),
            ],
        ),
    ]
