# Generated by Django 2.2.3 on 2019-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_order_ordergoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodname', models.CharField(max_length=200)),
                ('goodprice', models.IntegerField()),
                ('integral', models.IntegerField(default=0)),
                ('carbonreduction', models.IntegerField(default=0)),
            ],
        ),
    ]
