# Generated by Django 2.2.3 on 2019-07-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_cartgoods_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='over_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
