# Generated by Django 2.2.3 on 2019-07-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190718_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermsg',
            name='usergold',
            field=models.IntegerField(default=0),
        ),
    ]
