# Generated by Django 2.2.3 on 2019-07-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_order_allgold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allcarbonreduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='allintegral',
            field=models.IntegerField(default=0),
        ),
    ]
