# Generated by Django 2.2.3 on 2019-07-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointsfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='integral')),
                ('gold', models.IntegerField()),
                ('goodsname', models.CharField(max_length=100)),
                ('consumption', models.IntegerField()),
            ],
        ),
    ]
