# Generated by Django 2.2.3 on 2019-07-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-create_time',)},
        ),
    ]
