# Generated by Django 2.2.3 on 2019-07-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.RenameModel(
            old_name='Polls',
            new_name='PollsInfo',
        ),
        migrations.AddField(
            model_name='voteinfo',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollsInfo'),
        ),
    ]
