# Generated by Django 2.2.3 on 2019-07-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pollsuser'),
    ]

    operations = [
    ]
