# Generated by Django 2.2.3 on 2019-07-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190713_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsuser',
            name='useractive',
            field=models.BooleanField(default=True),
        ),
    ]
